version: "3.9"

services:
  angular_app:
    container_name: angular_app
    image: pee-angular_app:1.0.0
    build: ./ChallengeTechForbClient
    ports:
      - 4200:4200
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/challenge_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
volumes:
  mysql_data:
